from .coin import Coin


class Altcoin:
        # Initialize coins
    altcoins = {
        'avt': Coin('Aventus (AVT)'),
        'bch': Coin('Bitcoin Cash (BTH)'),
        'btc': Coin('Bitcoin (BTC)'),
        'btg': Coin('Bitcoin Gold (BTG)'),
        'dsh': Coin('Dash (DSH)'),
        'etc': Coin('Ethereum Classic (ETC)'),
        'eth': Coin('Ethereum (ETH)'),
        'eos': Coin('Eosio (EOS)'),
        'fun': Coin('FunFair (FUN)'),
        'gnt': Coin('Golem (GNT)'),
        'iot': Coin('Iota (IOT)'),
        'ltc': Coin('Litecoin (LTC)'),
        'neo': Coin('Neon (NEO)'),
        'omg': Coin('Omisego'),
        'qsh': Coin('QASH (QSH)'),
        'qtm': Coin('Qtum (QTM)'),
        'rcn': Coin('Ripio Credit Network (RCN)'),
        'rlc': Coin('iExec (RLC)'),
        'san': Coin('Santiment (SAN)'),
        'spk': Coin('SpankChain (SPK)'),
        'trx': Coin('Tron (TRX)'),
        'xlm': Coin('Stella Lumen (XLM)'),
        'xmr': Coin('Monero (XMR)'),
        'xrp': Coin('Ripple (XRP)'),
        'zec': Coin('Zcash (ZEC)'),
        'ada': Coin('Cardano (ADA)'),
        'xvg': Coin('Verge (XVG)'),
        'xem': Coin('NEM (XEM)'),
        'ven': Coin('VeChain (VEN)'),
        'bnb': Coin('Binance Coin (BNB)'),
        'bcn': Coin('Bytecoin (BCN)'),
        'icx': Coin('ICON (ICX)'),
        'lsk': Coin('Lisk (LSK)'),
        'zil': Coin('Zilliqa (ZIL)'),
        'ont': Coin('Ontology (ONT)'),
        'ae': Coin('Aeternity (AE)'),
        'zrx': Coin('Ox (ZRX)'),
        'dcr': Coin('Decred (DCR)'),
        'nano': Coin('Nano (NANO)'),
        'waves': Coin('Waves (WAVES)'),
        'elf': Coin('aelf (ELF'),
        'steem': Coin('Steem (STEEM)'),
        'mana': Coin('Decentraland (MANA)')
    }
